"""create initial domain schema

Revision ID: b7de57d19d14
Revises:
Create Date: 2026-08-31 18:04:39.627093+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7de57d19d14"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "address",
        sa.Column("street", sa.String(length=150), nullable=False),
        sa.Column("number", sa.String(length=10), nullable=False),
        sa.Column("complement", sa.String(length=100), nullable=True),
        sa.Column("neighborhood", sa.String(length=100), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.CHAR(length=2), nullable=False),
        sa.Column("zip_code", sa.CHAR(length=8), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_address")),
    )
    op.create_table(
        "app_user",
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "user_type",
            sa.Enum("candidate", "company", "administrator", name="user_type"),
            nullable=False,
        ),
        sa.Column(
            "account_status",
            sa.Enum("active", "suspended", "blocked", name="account_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("email", name=op.f("uq_app_user_email")),
    )
    op.create_index(
        op.f("ix_app_user_user_type"), "app_user", ["user_type"], unique=False
    )
    op.create_table(
        "skill",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.Enum("hard", "soft", name="skill_type"), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill")),
        sa.UniqueConstraint("name", "type", name=op.f("uq_skill_name_type")),
    )
    op.create_table(
        "training",
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("provider", sa.String(length=150), nullable=True),
        sa.Column("area", sa.String(length=100), nullable=True),
        sa.Column(
            "training_mode",
            sa.Enum("onsite", "hybrid", "remote", "online", name="training_mode"),
            nullable=True,
        ),
        sa.Column("workload_hours", sa.SmallInteger(), nullable=True),
        sa.Column("free", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("external_link", sa.Text(), nullable=False),
        sa.Column(
            "published", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training")),
    )
    op.create_index(
        op.f("ix_training_published"), "training", ["published"], unique=False
    )
    op.create_table(
        "administrator",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["app_user.id"],
            name=op.f("fk_administrator_id_app_user"),
            ondelete="CASCADE",
            initially="IMMEDIATE",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_administrator")),
    )
    op.create_table(
        "candidate",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column("cpf", sa.CHAR(length=11), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("age", sa.SmallInteger(), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.CHAR(length=2), nullable=True),
        sa.Column(
            "availability",
            sa.Enum("available", "unavailable", name="availability_status"),
            server_default="available",
            nullable=False,
        ),
        sa.Column(
            "accepts_automatic_application",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("terms_version_accepted", sa.String(length=20), nullable=True),
        sa.Column("terms_accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "birth_date <= CURRENT_DATE - INTERVAL '45 years'",
            name=op.f("ck_candidate_minimum_age"),
        ),
        sa.CheckConstraint("cpf ~ '^[0-9]{11}$'", name=op.f("ck_candidate_cpf_format")),
        sa.CheckConstraint(
            "age IS NULL OR age >= 45", name=op.f("ck_candidate_age_value")
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["app_user.id"],
            name=op.f("fk_candidate_id_app_user"),
            ondelete="CASCADE",
            initially="IMMEDIATE",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate")),
        sa.UniqueConstraint("cpf", name=op.f("uq_candidate_cpf")),
    )
    op.create_table(
        "company",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cnpj", sa.CHAR(length=14), nullable=False),
        sa.Column("legal_name", sa.String(length=200), nullable=False),
        sa.Column("trade_name", sa.String(length=200), nullable=True),
        sa.Column("primary_cnae", sa.String(length=10), nullable=True),
        sa.Column("corporate_email", sa.String(length=150), nullable=False),
        sa.Column(
            "corporate_email_confirmed",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("company_size", sa.String(length=30), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("linkedin_url", sa.Text(), nullable=True),
        sa.Column(
            "linkedin_verified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("address_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "approved", "rejected", "blocked", name="company_status"
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("terms_version_accepted", sa.String(length=20), nullable=True),
        sa.Column("terms_accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("cnpj ~ '^[0-9]{14}$'", name=op.f("ck_company_cnpj_format")),
        sa.CheckConstraint(
            "lower(split_part(corporate_email, '@', 2)) NOT IN ('gmail.com', 'hotmail.com', 'outlook.com', 'yahoo.com', 'icloud.com', 'bol.com.br', 'uol.com.br')",
            name=op.f("ck_company_corporate_email"),
        ),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["address.id"],
            name=op.f("fk_company_address_id_address"),
            ondelete="SET NULL",
            initially="IMMEDIATE",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["app_user.id"],
            name=op.f("fk_company_id_app_user"),
            ondelete="CASCADE",
            initially="IMMEDIATE",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company")),
        sa.UniqueConstraint("cnpj", name=op.f("uq_company_cnpj")),
        sa.UniqueConstraint("corporate_email", name=op.f("uq_company_corporate_email")),
    )
    op.create_index("ix_company_status", "company", ["status"], unique=False)
    op.create_table(
        "event",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=60), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_event_user_id_app_user"),
            ondelete="SET NULL",
            initially="IMMEDIATE",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event")),
    )
    op.create_index(op.f("ix_event_user_id"), "event", ["user_id"], unique=False)
    op.create_table(
        "notification",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=60), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "read", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_notification_user_id_app_user"),
            ondelete="CASCADE",
            initially="IMMEDIATE",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification")),
    )
    op.create_index(
        "ix_notification_user_id_read",
        "notification",
        ["user_id", "read"],
        unique=False,
    )
    op.create_table(
        "job",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "work_mode",
            sa.Enum("onsite", "hybrid", "remote", name="work_mode"),
            nullable=False,
        ),
        sa.Column("location", sa.String(length=150), nullable=True),
        sa.Column("contract_type", sa.String(length=50), nullable=True),
        sa.Column("salary_max", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "under_review",
                "published",
                "paused",
                "expired",
                "closed",
                name="job_status",
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closing_date", sa.Date(), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "hired_on_platform",
                "hired_elsewhere",
                "not_hired",
                "cancelled",
                name="job_outcome",
            ),
            nullable=True,
        ),
        sa.Column(
            "featured", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("featured_until", sa.Date(), nullable=True),
        sa.Column(
            "desired_skills",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
            name=op.f("fk_job_company_id_company"),
            ondelete="CASCADE",
            initially="IMMEDIATE",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job")),
    )
    op.create_index(op.f("ix_job_company_id"), "job", ["company_id"], unique=False)
    op.create_index(op.f("ix_job_status"), "job", ["status"], unique=False)
    op.create_table(
        "resume",
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "employment_status",
            sa.Enum("employed", "unemployed", name="employment_status"),
            nullable=True,
        ),
        sa.Column("employment_status_since", sa.Date(), nullable=True),
        sa.Column("desired_salary", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("availability_start_date", sa.Date(), nullable=True),
        sa.Column(
            "completion_percentage",
            sa.SmallInteger(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "skill_ids",
            sa.ARRAY(sa.UUID()),
            server_default=sa.text("'{}'::uuid[]"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "completion_percentage BETWEEN 0 AND 100",
            name=op.f("ck_resume_completion_percentage"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidate.id"],
            name=op.f("fk_resume_candidate_id_candidate"),
            ondelete="CASCADE",
            initially="IMMEDIATE",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resume")),
    )
    op.create_index(
        op.f("ix_resume_candidate_id"), "resume", ["candidate_id"], unique=True
    )
    op.create_table(
        "application",
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("active", "automatic", name="application_type"),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "applied",
                "under_review",
                "in_selection_process",
                "hired",
                "not_selected",
                "withdrawn",
                "expired",
                name="application_status",
            ),
            server_default="applied",
            nullable=False,
        ),
        sa.Column("match_score", sa.SmallInteger(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "match_score BETWEEN 0 AND 100", name=op.f("ck_application_match_score")
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidate.id"],
            name=op.f("fk_application_candidate_id_candidate"),
            ondelete="CASCADE",
            initially="IMMEDIATE",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
            name=op.f("fk_application_job_id_job"),
            ondelete="CASCADE",
            initially="IMMEDIATE",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application")),
        sa.UniqueConstraint(
            "candidate_id", "job_id", name=op.f("uq_application_candidate_id_job_id")
        ),
    )
    op.create_index(
        op.f("ix_application_candidate_id"),
        "application",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_job_id"), "application", ["job_id"], unique=False
    )
    op.create_table(
        "attached_certificate",
        sa.Column("file_url", sa.Text(), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resume_id", sa.UUID(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resume.id"],
            name=op.f("fk_attached_certificate_resume_id_resume"),
            ondelete="CASCADE",
            initially="IMMEDIATE",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attached_certificate")),
    )
    op.create_index(
        op.f("ix_attached_certificate_resume_id"),
        "attached_certificate",
        ["resume_id"],
        unique=False,
    )
    op.create_table(
        "certification",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("issuer", sa.String(length=150), nullable=True),
        sa.Column("issued_date", sa.Date(), nullable=True),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column("resume_id", sa.UUID(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resume.id"],
            name=op.f("fk_certification_resume_id_resume"),
            ondelete="CASCADE",
            initially="IMMEDIATE",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certification")),
    )
    op.create_index(
        op.f("ix_certification_resume_id"), "certification", ["resume_id"], unique=False
    )
    op.create_table(
        "education",
        sa.Column("institution", sa.String(length=150), nullable=False),
        sa.Column("degree", sa.String(length=100), nullable=True),
        sa.Column("field", sa.String(length=100), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("resume_id", sa.UUID(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resume.id"],
            name=op.f("fk_education_resume_id_resume"),
            ondelete="CASCADE",
            initially="IMMEDIATE",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_education")),
    )
    op.create_index(
        op.f("ix_education_resume_id"), "education", ["resume_id"], unique=False
    )
    op.create_table(
        "experience",
        sa.Column("company_name", sa.String(length=150), nullable=False),
        sa.Column("role", sa.String(length=150), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("resume_id", sa.UUID(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resume.id"],
            name=op.f("fk_experience_resume_id_resume"),
            ondelete="CASCADE",
            initially="IMMEDIATE",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experience")),
    )
    op.create_index(
        op.f("ix_experience_resume_id"), "experience", ["resume_id"], unique=False
    )
    op.create_table(
        "language",
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("proficiency", sa.String(length=30), nullable=True),
        sa.Column("resume_id", sa.UUID(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resume.id"],
            name=op.f("fk_language_resume_id_resume"),
            ondelete="CASCADE",
            initially="IMMEDIATE",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_language")),
    )
    op.create_index(
        op.f("ix_language_resume_id"), "language", ["resume_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_language_resume_id"), table_name="language")
    op.drop_table("language")
    op.drop_index(op.f("ix_experience_resume_id"), table_name="experience")
    op.drop_table("experience")
    op.drop_index(op.f("ix_education_resume_id"), table_name="education")
    op.drop_table("education")
    op.drop_index(op.f("ix_certification_resume_id"), table_name="certification")
    op.drop_table("certification")
    op.drop_index(
        op.f("ix_attached_certificate_resume_id"), table_name="attached_certificate"
    )
    op.drop_table("attached_certificate")
    op.drop_index(op.f("ix_application_job_id"), table_name="application")
    op.drop_index(op.f("ix_application_candidate_id"), table_name="application")
    op.drop_table("application")
    op.drop_index(op.f("ix_resume_candidate_id"), table_name="resume")
    op.drop_table("resume")
    op.drop_index(op.f("ix_job_status"), table_name="job")
    op.drop_index(op.f("ix_job_company_id"), table_name="job")
    op.drop_table("job")
    op.drop_index("ix_notification_user_id_read", table_name="notification")
    op.drop_table("notification")
    op.drop_index(op.f("ix_event_user_id"), table_name="event")
    op.drop_table("event")
    op.drop_index("ix_company_status", table_name="company")
    op.drop_table("company")
    op.drop_table("candidate")
    op.drop_table("administrator")
    op.drop_index(op.f("ix_training_published"), table_name="training")
    op.drop_table("training")
    op.drop_table("skill")
    op.drop_index(op.f("ix_app_user_user_type"), table_name="app_user")
    op.drop_table("app_user")
    op.drop_table("address")
    for enum_name in (
        "application_status",
        "application_type",
        "employment_status",
        "job_outcome",
        "job_status",
        "work_mode",
        "company_status",
        "availability_status",
        "training_mode",
        "skill_type",
        "account_status",
        "user_type",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=False)
