"""add email verification request table

Revision ID: 4c0aff4894d7
Revises: 974c1d45de00
Create Date: 2026-09-09 04:07:30.974300+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c0aff4894d7"
down_revision: str | Sequence[str] | None = "974c1d45de00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_verification_request",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_email_verification_request_user_id_app_user"),
            ondelete="CASCADE",
            initially="IMMEDIATE",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_verification_request")),
    )
    op.create_index(
        "ix_email_verification_request_user_id_created_at",
        "email_verification_request",
        ["user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_email_verification_request_user_id_created_at",
        table_name="email_verification_request",
    )
    op.drop_table("email_verification_request")
    # ### end Alembic commands ###
