"""add email verification timestamp to app user

Revision ID: 974c1d45de00
Revises: b7de57d19d14
Create Date: 2026-09-09 04:02:22.942340+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "974c1d45de00"
down_revision: str | Sequence[str] | None = "b7de57d19d14"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_user",
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_user", "email_verified_at")
    # ### end Alembic commands ###
